info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-01-26T19:42:46.421Z"}
info: Connected to the database. {"timestamp":"2023-01-26T19:42:48.866Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-01-26T19:44:02.525Z"}
info: Connected to the database. {"timestamp":"2023-01-26T19:44:04.917Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-01-26T19:46:37.528Z"}
info: Connected to the database. {"timestamp":"2023-01-26T19:46:40.174Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-01-26T19:46:47.128Z"}
info: Connected to the database. {"timestamp":"2023-01-26T19:46:49.799Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-01-26T19:48:38.589Z"}
info: Connected to the database. {"timestamp":"2023-01-26T19:48:41.051Z"}
error: 
    status - 500 
    message - ValidationError: "firstname" length must be at least 4 characters long 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-26T19:49:12.312Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: shashank606.users index: email_1 dup key: { email: "neeraj@gmail.com" } 
      url - /api/v1/users 
      method - POST 
      IP - ::1
     {"timestamp":"2023-01-26T19:49:19.407Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.writeHead (node:_http_server:343:11)
    at ServerResponse.writeHead (D:\Java Script\FundoNotes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:334:8)
    at write_ (node:_http_outgoing:867:9)
    at ServerResponse.end (node:_http_outgoing:977:5)
    at ServerResponse.send (D:\Java Script\FundoNotes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\Java Script\FundoNotes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (D:\Java Script\FundoNotes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:326:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:473:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-26T19:49:19.419Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-01-26T19:50:58.780Z"}
info: Connected to the database. {"timestamp":"2023-01-26T19:51:01.295Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-01-26T19:59:10.324Z"}
info: Connected to the database. {"timestamp":"2023-01-26T19:59:12.898Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-01-26T20:11:25.822Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:11:28.398Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-01-26T20:12:26.084Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:12:28.769Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-01-26T20:12:33.119Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:12:35.732Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-01-26T20:13:05.355Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:13:07.867Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-01-26T20:13:20.440Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-01-26T20:13:25.402Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:13:27.753Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:14:03.309Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:14:32.877Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:14:35.412Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:16:23.830Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:16:26.318Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:17:59.020Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:18:01.625Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:19:14.991Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:19:17.367Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:19:22.740Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:19:28.343Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:19:31.211Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:19:50.046Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:19:52.469Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:20:32.913Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:20:35.458Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:24:45.288Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:24:50.433Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:26:56.060Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:26:58.760Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:27:28.822Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:27:31.529Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:27:35.982Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:27:38.806Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:28:12.092Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:28:14.450Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:28:32.144Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:28:37.875Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:28:40.374Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:29:38.443Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:29:40.792Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:31:11.368Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:31:14.301Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:31:29.972Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:31:32.735Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:32:08.011Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:32:10.669Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:33:39.055Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:33:41.805Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:36:11.379Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:36:14.076Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:37:08.515Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:37:11.266Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:37:57.366Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:37:59.805Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:38:57.530Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:39:00.049Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:39:29.152Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:39:31.605Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:40:37.732Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:40:40.347Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:41:41.159Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:41:43.847Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:43:14.850Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:43:17.389Z"}
error: 
    status - 500 
    message - ValidationError: "firstname" is required 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-26T20:44:37.720Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: shashank606.users index: email_1 dup key: { email: "neera@gmail.com" } 
      url - /api/v1/users/register 
      method - POST 
      IP - ::1
     {"timestamp":"2023-01-26T20:44:54.058Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.writeHead (node:_http_server:343:11)
    at ServerResponse.writeHead (D:\Java Script\FundoNotes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:334:8)
    at write_ (node:_http_outgoing:867:9)
    at ServerResponse.end (node:_http_outgoing:977:5)
    at ServerResponse.send (D:\Java Script\FundoNotes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\Java Script\FundoNotes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (D:\Java Script\FundoNotes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:326:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:646:15
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:265:14)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:646:15
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:265:14)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:136:14)
    at _callee3$ (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:61:5)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.throw (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _throw (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-26T20:44:54.071Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:46:21.151Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:46:24.007Z"}
error: 
    status - 500 
    message - ReferenceError: bcrypt is not defined
    at _callee2$ (D:\Java Script\FundoNotes\src\services\/user.service.js:10:35)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.newUser (D:\Java Script\FundoNotes\src\services\/user.service.js:10:21)
    at _callee3$ (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:54:36)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at newUser (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:52:21)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at newUserValidator (D:\Java Script\FundoNotes\src\validators\/user.validator.js:15:5)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\Java Script\FundoNotes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at D:\Java Script\FundoNotes\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:231:16)
    at done (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28) 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-26T20:46:37.138Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:47:09.919Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:47:12.611Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:48:23.443Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:48:25.927Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:48:59.468Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:49:01.774Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:50:14.346Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:50:16.861Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:50:32.453Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:50:35.157Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:54:57.485Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:55:00.056Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:55:10.165Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:55:12.657Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:55:17.383Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:55:22.626Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:55:26.640Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:55:28.897Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:56:34.615Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:56:37.349Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:57:07.038Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:57:09.685Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T20:57:28.318Z"}
info: Connected to the database. {"timestamp":"2023-01-26T20:57:30.902Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T21:00:32.463Z"}
info: Connected to the database. {"timestamp":"2023-01-26T21:00:35.097Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token } in JSON at position 72
    at JSON.parse (<anonymous>)
    at parse (D:\Java Script\FundoNotes\node_modules\body-parser\lib\types\json.js:89:19)
    at D:\Java Script\FundoNotes\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:231:16)
    at done (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/login/log 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-26T21:01:24.033Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T21:03:36.688Z"}
info: Connected to the database. {"timestamp":"2023-01-26T21:03:39.439Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T21:03:44.193Z"}
info: Connected to the database. {"timestamp":"2023-01-26T21:03:46.495Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T21:08:18.109Z"}
info: Connected to the database. {"timestamp":"2023-01-26T21:08:20.722Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T21:10:20.367Z"}
info: Connected to the database. {"timestamp":"2023-01-26T21:10:22.898Z"}
error: 
    status - 500 
    message - ReferenceError: joiPassword is not defined
    at LoginValidator (D:\Java Script\FundoNotes\src\validators\/user.validator.js:22:15)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\Java Script\FundoNotes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at D:\Java Script\FundoNotes\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:231:16)
    at done (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1//users/login/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-26T21:10:33.359Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T21:11:23.406Z"}
info: Connected to the database. {"timestamp":"2023-01-26T21:11:25.720Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'string')
    at LoginValidator (D:\Java Script\FundoNotes\src\validators\/user.validator.js:22:27)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\Java Script\FundoNotes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at D:\Java Script\FundoNotes\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:231:16)
    at done (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1//users/login/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-26T21:11:26.266Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T21:13:26.407Z"}
info: Connected to the database. {"timestamp":"2023-01-26T21:13:29.112Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T21:13:54.132Z"}
info: Connected to the database. {"timestamp":"2023-01-26T21:13:56.559Z"}
error: 
    status - 500 
    message - ReferenceError: joiPassword is not defined
    at LoginValidator (D:\Java Script\FundoNotes\src\validators\/user.validator.js:23:15)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\Java Script\FundoNotes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at D:\Java Script\FundoNotes\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:231:16)
    at done (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1//users/login/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-26T21:14:03.654Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T21:14:20.876Z"}
info: Connected to the database. {"timestamp":"2023-01-26T21:14:23.326Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T21:29:49.168Z"}
info: Connected to the database. {"timestamp":"2023-01-26T21:29:51.936Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: shashank606.users index: email_1 dup key: { email: "Shashank@gmail.com" } 
      url - /api/v1//users/register/ 
      method - POST 
      IP - ::1
     {"timestamp":"2023-01-26T21:31:05.940Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.writeHead (node:_http_server:343:11)
    at ServerResponse.writeHead (D:\Java Script\FundoNotes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:334:8)
    at write_ (node:_http_outgoing:867:9)
    at ServerResponse.end (node:_http_outgoing:977:5)
    at ServerResponse.send (D:\Java Script\FundoNotes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\Java Script\FundoNotes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (D:\Java Script\FundoNotes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:326:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:473:21) 
    url - /api/v1//users/register/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-26T21:31:05.953Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T21:35:04.610Z"}
info: Connected to the database. {"timestamp":"2023-01-26T21:35:07.839Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: shashank606.users index: email_1 dup key: { email: "Shashandfsdfk@gmail.com" } 
      url - /api/v1//users/register/ 
      method - POST 
      IP - ::1
     {"timestamp":"2023-01-26T21:35:18.243Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.writeHead (node:_http_server:343:11)
    at ServerResponse.writeHead (D:\Java Script\FundoNotes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:334:8)
    at write_ (node:_http_outgoing:867:9)
    at ServerResponse.end (node:_http_outgoing:977:5)
    at ServerResponse.send (D:\Java Script\FundoNotes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\Java Script\FundoNotes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (D:\Java Script\FundoNotes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:326:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:473:21) 
    url - /api/v1//users/register/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-26T21:35:18.256Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T21:36:10.769Z"}
info: Connected to the database. {"timestamp":"2023-01-26T21:36:13.382Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: shashank606.users index: email_1 dup key: { email: "Shashandfsdfk@gmail.com" } 
      url - /api/v1//users/register/ 
      method - POST 
      IP - ::1
     {"timestamp":"2023-01-26T21:36:15.932Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.writeHead (node:_http_server:343:11)
    at ServerResponse.writeHead (D:\Java Script\FundoNotes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:334:8)
    at write_ (node:_http_outgoing:867:9)
    at ServerResponse.end (node:_http_outgoing:977:5)
    at ServerResponse.send (D:\Java Script\FundoNotes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\Java Script\FundoNotes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (D:\Java Script\FundoNotes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:326:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:473:21) 
    url - /api/v1//users/register/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-26T21:36:15.939Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T21:38:06.423Z"}
info: Connected to the database. {"timestamp":"2023-01-26T21:38:08.924Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: shashank606.users index: email_1 dup key: { email: "Shashandfsdfk@gmail.com" } 
      url - /api/v1//users/register/ 
      method - POST 
      IP - ::1
     {"timestamp":"2023-01-26T21:38:12.975Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.writeHead (node:_http_server:343:11)
    at ServerResponse.writeHead (D:\Java Script\FundoNotes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:334:8)
    at write_ (node:_http_outgoing:867:9)
    at ServerResponse.end (node:_http_outgoing:977:5)
    at ServerResponse.send (D:\Java Script\FundoNotes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\Java Script\FundoNotes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (D:\Java Script\FundoNotes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:326:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:473:21) 
    url - /api/v1//users/register/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-26T21:38:12.986Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: shashank606.users index: email_1 dup key: { email: "Shashandfsdfk@gmail.com" } 
      url - /api/v1//users/register/ 
      method - POST 
      IP - ::1
     {"timestamp":"2023-01-26T21:38:15.496Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.writeHead (node:_http_server:343:11)
    at ServerResponse.writeHead (D:\Java Script\FundoNotes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:334:8)
    at write_ (node:_http_outgoing:867:9)
    at ServerResponse.end (node:_http_outgoing:977:5)
    at ServerResponse.send (D:\Java Script\FundoNotes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\Java Script\FundoNotes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (D:\Java Script\FundoNotes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:326:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:473:21) 
    url - /api/v1//users/register/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-26T21:38:15.499Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T21:45:20.664Z"}
info: Connected to the database. {"timestamp":"2023-01-26T21:45:23.264Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: shashank606.users index: email_1 dup key: { email: "Shashandfsdfk@gmail.com" } 
      url - /api/v1//users/register/ 
      method - POST 
      IP - ::1
     {"timestamp":"2023-01-26T21:45:32.160Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.writeHead (node:_http_server:343:11)
    at ServerResponse.writeHead (D:\Java Script\FundoNotes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:334:8)
    at write_ (node:_http_outgoing:867:9)
    at ServerResponse.end (node:_http_outgoing:977:5)
    at ServerResponse.send (D:\Java Script\FundoNotes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\Java Script\FundoNotes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (D:\Java Script\FundoNotes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:326:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:473:21) 
    url - /api/v1//users/register/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-26T21:45:32.171Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: shashank606.users index: email_1 dup key: { email: "Shashandfsdfk@gmail.com" } 
      url - /api/v1//users/register/ 
      method - POST 
      IP - ::1
     {"timestamp":"2023-01-26T21:45:34.402Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.writeHead (node:_http_server:343:11)
    at ServerResponse.writeHead (D:\Java Script\FundoNotes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:334:8)
    at write_ (node:_http_outgoing:867:9)
    at ServerResponse.end (node:_http_outgoing:977:5)
    at ServerResponse.send (D:\Java Script\FundoNotes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (D:\Java Script\FundoNotes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (D:\Java Script\FundoNotes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:326:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:473:21) 
    url - /api/v1//users/register/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-26T21:45:34.405Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T21:46:59.078Z"}
info: Connected to the database. {"timestamp":"2023-01-26T21:47:04.218Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T21:48:13.388Z"}
info: Connected to the database. {"timestamp":"2023-01-26T21:48:15.741Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T21:49:01.834Z"}
info: Connected to the database. {"timestamp":"2023-01-26T21:49:04.446Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-26T21:49:10.978Z"}
info: Connected to the database. {"timestamp":"2023-01-26T21:49:13.614Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-27T12:10:37.102Z"}
info: Connected to the database. {"timestamp":"2023-01-27T12:10:39.553Z"}
error: 
    status - 500 
    message - ReferenceError: res is not defined
    at _callee3$ (D:\Java Script\FundoNotes\src\services\/user.service.js:32:5)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.login (D:\Java Script\FundoNotes\src\services\/user.service.js:19:19)
    at _callee4$ (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:129:36)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at login (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:127:19)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\Java Script\FundoNotes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at D:\Java Script\FundoNotes\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:231:16)
    at done (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1//users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-27T12:10:51.197Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-27T12:12:01.547Z"}
info: Connected to the database. {"timestamp":"2023-01-27T12:12:04.241Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-27T12:12:07.737Z"}
info: Connected to the database. {"timestamp":"2023-01-27T12:12:10.276Z"}
error: 
    status - 500 
    message - ReferenceError: res is not defined
    at _callee3$ (D:\Java Script\FundoNotes\src\services\/user.service.js:32:5)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.login (D:\Java Script\FundoNotes\src\services\/user.service.js:19:19)
    at _callee4$ (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:129:36)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at login (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:127:19)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\Java Script\FundoNotes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at D:\Java Script\FundoNotes\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:231:16)
    at done (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1//users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-27T12:12:12.587Z"}
error: 
    status - 500 
    message - ReferenceError: res is not defined
    at _callee3$ (D:\Java Script\FundoNotes\src\services\/user.service.js:32:5)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.login (D:\Java Script\FundoNotes\src\services\/user.service.js:19:19)
    at _callee4$ (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:129:36)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at login (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:127:19)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\Java Script\FundoNotes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at D:\Java Script\FundoNotes\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:231:16)
    at done (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1//users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-27T12:12:14.315Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-27T12:12:28.818Z"}
info: Connected to the database. {"timestamp":"2023-01-27T12:12:31.672Z"}
error: 
    status - 500 
    message - ReferenceError: res is not defined
    at _callee3$ (D:\Java Script\FundoNotes\src\services\/user.service.js:32:5)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.login (D:\Java Script\FundoNotes\src\services\/user.service.js:19:19)
    at _callee4$ (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:129:36)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at login (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:127:19)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\Java Script\FundoNotes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at D:\Java Script\FundoNotes\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:231:16)
    at done (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1//users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-27T12:12:33.434Z"}
error: 
    status - 500 
    message - ReferenceError: res is not defined
    at _callee3$ (D:\Java Script\FundoNotes\src\services\/user.service.js:32:5)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.login (D:\Java Script\FundoNotes\src\services\/user.service.js:19:19)
    at _callee4$ (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:129:36)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at login (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:127:19)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\Java Script\FundoNotes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at D:\Java Script\FundoNotes\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:231:16)
    at done (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1//users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-27T12:12:34.631Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-27T12:12:57.356Z"}
info: Connected to the database. {"timestamp":"2023-01-27T12:12:59.800Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-27T12:13:46.841Z"}
info: Connected to the database. {"timestamp":"2023-01-27T12:13:49.515Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-27T12:13:55.491Z"}
info: Connected to the database. {"timestamp":"2023-01-27T12:13:58.145Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-27T12:14:01.762Z"}
info: Connected to the database. {"timestamp":"2023-01-27T12:14:05.021Z"}
error: 
    status - 500 
    message - TypeError: _context3.t0 is not a constructor
    at _callee3$ (D:\Java Script\FundoNotes\src\services\/user.service.js:32:11)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.login (D:\Java Script\FundoNotes\src\services\/user.service.js:19:19)
    at _callee4$ (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:129:36)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at login (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:127:19)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\Java Script\FundoNotes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at D:\Java Script\FundoNotes\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:231:16)
    at done (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1//users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-27T12:14:12.208Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-27T12:14:59.887Z"}
info: Connected to the database. {"timestamp":"2023-01-27T12:15:02.496Z"}
error: 
    status - 500 
    message - TypeError: _context3.t0 is not a constructor
    at _callee3$ (D:\Java Script\FundoNotes\src\services\/user.service.js:32:11)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.login (D:\Java Script\FundoNotes\src\services\/user.service.js:19:19)
    at _callee4$ (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:129:36)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at login (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:127:19)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\Java Script\FundoNotes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at D:\Java Script\FundoNotes\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:231:16)
    at done (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1//users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-27T12:15:05.984Z"}
error: 
    status - 500 
    message - TypeError: _context3.t0 is not a constructor
    at _callee3$ (D:\Java Script\FundoNotes\src\services\/user.service.js:32:11)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.login (D:\Java Script\FundoNotes\src\services\/user.service.js:19:19)
    at _callee4$ (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:129:36)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at login (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:127:19)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Java Script\FundoNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\Java Script\FundoNotes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\Java Script\FundoNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:328:13)
    at D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Java Script\FundoNotes\node_modules\express\lib\router\index.js:280:10)
    at D:\Java Script\FundoNotes\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:231:16)
    at done (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\Java Script\FundoNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1//users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-27T12:15:07.398Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-27T12:15:19.362Z"}
info: Connected to the database. {"timestamp":"2023-01-27T12:15:22.462Z"}
error: 
    status - 500 
    message - TypeError: _context3.t0 is not a constructor
    at _callee3$ (D:\Java Script\FundoNotes\src\services\/user.service.js:32:11)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.login (D:\Java Script\FundoNotes\src\services\/user.service.js:19:19)
    at _callee4$ (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:129:36)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1//users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-27T12:15:24.989Z"}
error: 
    status - 500 
    message - TypeError: _context3.t0 is not a constructor
    at _callee3$ (D:\Java Script\FundoNotes\src\services\/user.service.js:32:11)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.login (D:\Java Script\FundoNotes\src\services\/user.service.js:19:19)
    at _callee4$ (D:\Java Script\FundoNotes\src\controllers\/user.controller.js:129:36)
    at tryCatch (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\Java Script\FundoNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1//users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2023-01-27T12:15:26.151Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-27T12:16:38.490Z"}
info: Connected to the database. {"timestamp":"2023-01-27T12:16:46.187Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-27T12:17:13.824Z"}
info: Connected to the database. {"timestamp":"2023-01-27T12:17:16.041Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-27T12:37:51.525Z"}
info: Connected to the database. {"timestamp":"2023-01-27T12:37:54.403Z"}
info: Server started at http://localhost:6000/api/v1/ {"timestamp":"2023-01-27T12:41:14.858Z"}
info: Connected to the database. {"timestamp":"2023-01-27T12:41:17.374Z"}
